### ISSUE TITLE
One link in "gold166_v1" version is not valid

### ISSUE THREAD

**Issue by jifaley** [BigNeuron/Data#1]
Dear group,
    I find that the link in "Asia/Beijing (Beijing Univ. of Tech.): http://wici.bjut.edu.cn/bigneuron/gold166.zip" 
in the "gold166_v1" release is not valid.

**Comment by hanchuan** [comment]
Thanks for the heads-up. It will be hard to keep every link valid after five or six years. However we are working on uploading much more data to a more permanent location for sharing.

**Comment by Elsword016** [comment]
Other links :
North America (Washington State University): http://dive.eecs.wsu.edu/bigneuron/gold166.zip
Asia/Singapore (A*Star): http://web.bii.a-star.edu.sg/bigneuron/gold166.zip
Asia/Beijing (Beijing Univ. of Tech.): http://wici.bjut.edu.cn/bigneuron/gold166.zip

Also not working

**Comment by lmanubens** [comment]
Asia/Singapore (A*Star): http://web.bii.a-star.edu.sg/bigneuron/gold166.zip works in our tests.

We have updated the list to remove the other two broken links.
We are also working on adding new mirrored sites and will update the list as soon as possible.

Thanks.
