### ISSUE TITLE
Add explanatory note of zip format

### ISSUE THREAD

**Issue by kdmarrett** [BigNeuron/Data#3]
Please advise users on the release note for bigneuron dataset that the zip file for gold166.zip is zipped with a linux program so it has to be unzipped from a unix shell like WSL or linux itself with the 'zip' program.

As it stands all windows users who expect a standard zip file will see the message "zip ... is invalid"

**Comment by hanchuan** [comment]
Thanks for the suggestion.

**Comment by lmanubens** [comment]
Indeed, thanks for the suggestion, the information has been added to the wiki page.
