### ISSUE TITLE
Are the gold166 already fully preprocessed?

### ISSUE THREAD

**Issue by kdmarrett** [BigNeuron/Data#5]
The release documentation mentions that these gold166 images are "raw" does that mean that have not been preprocessed in the same way they were during comparison of reconstruction algorithms?

I ask because the recent BigNeuron Nature Methods paper mentions that the test image set used Brainbow color separation and 8-bit conversion. 

I'd like to confirm, if I run an alternate algorithm directly on these raw gold166 will it be an apples to apples comparison with the accuracy metrics shown in the paper?

Thank you again for providing such a valuable resource to benchmark with.

**Comment by lmanubens** [comment]
Dear Karl,

The analysis of the paper was done on the automated reconstructions obtained in the raw images of the data release (https://github.com/BigNeuron/Data/releases/tag/Gold166_v1).

Thus, if you run your tracing algorithm in the release data image stacks you should be comparing apples to apples.

We will refine the description of the release. You are right, those image stacks have been processed in some cases, such as the color separation you mentioned. 

Please, let us know if you have further questions!

**Comment by kdmarrett** [comment]
Perfect, just wanted to confirm thank you
