### ISSUE TITLE
Pixel size info missing from gold166 release

### ISSUE THREAD

**Issue by kdmarrett** [BigNeuron/Data#6]
Can you add the pixelsize.txt files for zebrafish_larve_RGC_UW and utokyo_fly? The pixel size information is still not included in the latest release.

Thank you,

**Comment by kdmarrett** [comment]
Also for the human_culturedcell_Cambridge_in_vitro folder, Series009, 17, 19, and 21, images are missing the pixel size
from the corresponding excel sheet, can you share what they are?

**Comment by kdmarrett** [comment]
It's also very difficult to match up the image folders in the fruitfly larvae gmu with the excel sheet rows provided for that data sheet without having intimate knowledge of the dataset. Do you have an internal copy of the pixel sizes somewhere? From the manuscript and shiny app it appears that this is process is automated on your end, yet I can not repeat the same analysis on the data. Can you share your copy of the pixel info data so that we can also automate our tests?

**Comment by kdmarrett** [comment]
Just following up, can you provide a new release with the full pixel size info of the datasets so others can use it as a resource? 

Thank you again for your efforts.

**Comment by lmanubens** [comment]
Dear Karl, 

Apologies for the very late reply! For some reason I missed any notifications for these issues.
The pixel sizes for the Gold166 dataset can be found at:
https://github.com/lmanubens/BigNeuron/blob/main/scaling_gold.csv
(as mentioned in the methods text of the Nature Methods manuscript)

Best!
Linus

**Comment by kdmarrett** [comment]
Thank you!
